# ===============================================
# MOTIONTRACKER - CONFIGURAÇÃO PROMETHEUS
# ===============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Monitoramento do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento do Backend NestJS
  - job_name: 'motiontracker-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Monitoramento do Frontend Next.js
  - job_name: 'motiontracker-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Monitoramento do Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Monitoramento do Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Node Exporter (se disponível)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']